version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- directory: /
  package-ecosystem: gomod
  schedule:
    interval: daily
- directory: /
  package-ecosystem: github-actions
  schedule:
    interval: daily
